# MoE Routing Production Configuration
# Validated for 4.72x stability improvement

api:
  host: "0.0.0.0"
  port: 8000
  workers: 1  # Single worker for controller state consistency
  log_level: "info"
  reload: false
  access_log: true

# Controller Configuration
controller:
  # Stability Parameters (validated)
  beta_min: 0.3      # Minimum gating sharpness
  beta_max: 1.0      # Maximum gating sharpness  
  lambda_min: 0.85   # Minimum EMA inertia
  lambda_max: 0.95   # Maximum EMA inertia
  
  # Performance Thresholds
  target_gating_sensitivity: 0.1    # Target under high ambiguity
  target_winner_flip_rate: 0.05     # Stability threshold
  max_processing_time_ms: 50        # Latency limit
  
  # Validation Settings
  improvement_target: 4.0           # Minimum improvement factor required
  validation_interval_hours: 24     # How often to run validation
  
  # Memory Management
  metrics_history_limit: 10000      # Keep recent metrics in memory
  cleanup_interval_minutes: 60     # Memory cleanup frequency

# Monitoring Configuration  
monitoring:
  metrics_enabled: true
  detailed_logging: true
  performance_tracking: true
  
  # Export Configuration
  export_interval_seconds: 60      # Metrics export frequency
  export_format: "jsonl"          # json, jsonl, prometheus
  
  # Alert Thresholds
  alerts:
    high_gating_sensitivity: 0.15   # Alert if exceeded
    high_flip_rate: 0.08            # Alert threshold
    high_latency_ms: 100            # Latency alert
    low_improvement_factor: 3.5     # Below target alert

# Logging Configuration
logging:
  version: 1
  disable_existing_loggers: false
  
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"
  
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/moe-routing.log
      mode: a
  
  loggers:
    "":
      level: INFO
      handlers: [console, file]
      propagate: false
    
    "src.core.production_controller":
      level: DEBUG
      handlers: [console, file]
      propagate: false
    
    "src.api.server":
      level: INFO
      handlers: [console, file]
      propagate: false

# Security Configuration
security:
  allowed_hosts: ["*"]  # Restrict in production
  max_request_size_mb: 10
  rate_limit:
    requests_per_minute: 1000
    burst_limit: 100
  
  # CORS Settings
  cors:
    allow_origins: ["*"]  # Restrict in production
    allow_methods: ["GET", "POST"]
    allow_headers: ["*"]
    allow_credentials: true

# Resource Limits
resources:
  max_memory_mb: 512
  max_cpu_percent: 50
  max_concurrent_requests: 100
  request_timeout_seconds: 30

# Development Overrides (remove for production)
development:
  reload: true
  log_level: "debug"
  detailed_errors: true
  cors_allow_all: true