# Simple Production Configuration for MoE Router V3
# Recommended for 90% of users - Production-ready with validated settings

# Backend Configuration (Single, optimized)
backend:
  type: "ollama"  # Most common and well-tested
  model: "qwen2.5:7b"  # Validated for A*→G mechanism
  host: "localhost"
  port: 11434
  timeout: 30
  
  # Connection settings
  max_connections: 10
  retry_attempts: 3
  retry_delay: 1.0

# Controller Configuration (Validated 4.72× improvement)
controller:
  type: "v3_pi_spike_guard"
  improvement_target: 4.72  # Validated target
  
  # Core parameters (production-optimized)
  beta_min: 0.85
  beta_max: 1.65
  lambda_min: 0.25
  lambda_max: 0.75
  
  # PI Controller (proven settings)
  pi_controller:
    enabled: true
    target_G_high_ambiguity: 0.60
    activation_threshold: 0.7
    k_p: 0.12
    k_i: 0.02
  
  # Spike Guard (stability protection)
  spike_guard:
    enabled: true
    threshold: 2.5
    trigger_count: 3
    hold_ticks: 5
  
  # Safety mechanisms
  safety:
    G_p99_cap: 5.0
    auto_revert_threshold: 2
    s_matrix_freeze_threshold: 0.7

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1  # Single worker for state consistency
  
  # Performance settings
  request_timeout: 30
  max_request_size: "10MB"
  
  # CORS (for dashboard access)
  cors:
    enabled: true
    origins: ["http://localhost:3000", "https://dashboard.company.com"]

# Telemetry (Essential only)
telemetry:
  enabled: true
  format: "jsonl"
  output_dir: "telemetry/events"
  buffer_size: 100
  flush_interval: 60
  
  # Essential metrics only
  include_mediation: true
  include_detailed_routing: false
  include_expert_weights: false

# Monitoring
monitoring:
  dashboard:
    enabled: true
    port: 3000
    auto_refresh: true
    
  # Basic alerting
  alerts:
    enabled: true
    config_file: "config/basic_alerts.yaml"
    
    # Critical alerts only
    channels: ["slack", "email"]
    
  # Health checks
  health_check:
    enabled: true
    interval: 60
    endpoint: "/health"

# Deployment Mode
deployment:
  mode: "production"
  environment: "prod"
  
  # Validation on startup
  validate_improvement: true
  validate_mediation: false  # Skip for faster startup
  
  # Logging
  log_level: "INFO"
  log_format: "json"
  log_file: "/var/log/moe-router/app.log"

# Feature Flags (Simple defaults)
features:
  counterfactual_replay: false
  advanced_mediation_analysis: false
  multi_backend_support: false
  experimental_controllers: false
  
  # Production features
  auto_revert: true
  spike_guard: true
  pi_control: true